### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by MaximeRDY** [wende/autocomplete-elixir#116]
Hello, 

Thanks for your package.

I found an issue.

1. Open Elixir File

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package 1.5.15

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/maxime/.atom/packages/autocomplete-elixir/lib/alchemide/doendmatcher.coffee:17

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.handleMatch (/packages/autocomplete-elixir/lib/alchemide/doendmatcher.coffee:17:35)
    at /packages/autocomplete-elixir/lib/autocomplete-elixir-client.coffee:21:23
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2187:33)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app/src/selection.js:920:27)
    at /Applications/Atom.app/Contents/Resources/app/src/selection.js:41:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:248:33)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:53:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:424:26)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:365:18)
    at MarkerLayer.module.exports.MarkerLayer.restoreFromSnapshot (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:282:24)
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1516:85)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:950:20)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:902:20)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1672:32)
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2173:25)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1968:25)
    at TextEditorComponent.didMouseDownOnContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1755:25)
```

### Commands

```
     -0:09.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.5 
atom-css-comb 3.3.1 
atom-elixir 0.2.3 
autocomplete-elixir 1.5.15 
autocomplete-ruby 0.2.8 
build-elixir 0.7.0 
busy-signal 1.4.3 
css-snippets 1.1.0 
elm-format 2.2.0 
elmjutsu 5.6.2 
file-icons 2.1.10 
git-time-machine 1.5.9 
goto-definition 1.3.4 
hyperclick 0.1.3 
intentions 1.1.5 
js-hyperclick 1.11.0 
language-docker 1.1.8 
language-elixir 0.19.0 
language-elm 1.5.0 
language-haml 0.25.1 
language-rspec 0.6.3 
linter 2.2.0 
linter-coffeelint 1.2.1 
linter-elixirc 1.7.0 
linter-elm-make 0.23.7 
linter-ruby 1.2.5 
linter-swagger 0.4.1 
linter-ui-default 1.6.5 
monokai 0.24.0 
pigments 0.40.2 
platformio-ide-terminal 2.5.5 
project-manager 3.3.5 
rails-i18n-autocomplete 0.4.0 
rails-snippets 2.16.0 
rspec-snippets 0.4.0 
ruby-test 1.0.2 
script 3.15.0 
set-syntax 0.3.2 
trailing-spaces 0.4.0 
xml-formatter 0.11.0 
```

**Comment by MaximeRDY** [comment]
Oups duplicate
