### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by syamilmj** [wende/autocomplete-elixir#119]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package 1.5.15

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/syamilmj/.atom/packages/autocomplete-elixir/lib/alchemide/doendmatcher.coffee:17

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.handleMatch (/packages/autocomplete-elixir/lib/alchemide/doendmatcher.coffee:17:35)
    at /packages/autocomplete-elixir/lib/autocomplete-elixir-client.coffee:21:23
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2188:33)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app/src/selection.js:920:27)
    at /Applications/Atom.app/Contents/Resources/app/src/selection.js:41:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:248:33)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:53:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:424:26)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:365:18)
    at MarkerLayer.module.exports.MarkerLayer.restoreFromSnapshot (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:282:24)
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1516:85)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:950:20)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:902:20)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2174:25)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1969:25)
    at TextEditorComponent.didMouseDownOnContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1776:25)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.5 
atom-elixir 0.2.3 
autocomplete-elixir 1.5.15 
busy-signal 1.4.3 
emmet 2.4.3 
git-blame 1.2.1 
intentions 1.1.2 
language-apache 1.7.0 
language-babel 2.68.0 
language-elixir 0.19.0 
language-erlang 3.2.0 
language-javascript-jsx 0.3.7 
language-slim 0.5.0 
linter 2.2.0 
linter-elixirc 1.7.0 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.7 
minimap 4.29.6 
php-cs-fixer 4.1.0 
remote-edit 1.9.0 
split-diff 1.4.4 
Sublime-Style-Column-Selection 1.7.4 
tab-control 0.6.10 
tabs-to-spaces 1.0.3 
tidy-tabs 0.3.0 
```

**Comment by syamilmj** [comment]
Sorry, didn't realize this package has been deprecated.
