### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jclem** [wende/autocomplete-elixir#147]
[Enter steps to reproduce:]

1. Open any Elixir file.
2. Click anywhere in the file.

**Atom**: 1.19.6 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package 1.5.15

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/jclem/.atom/packages/autocomplete-elixir/lib/alchemide/doendmatcher.coffee:17

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.handleMatch (/packages/autocomplete-elixir/lib/alchemide/doendmatcher.coffee:17:35)
    at /packages/autocomplete-elixir/lib/autocomplete-elixir-client.coffee:21:23
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2188:33)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app/src/selection.js:920:27)
    at /Applications/Atom.app/Contents/Resources/app/src/selection.js:41:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:248:33)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:53:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:424:26)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:365:18)
    at MarkerLayer.module.exports.MarkerLayer.restoreFromSnapshot (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:290:24)
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1526:85)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:948:20)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:897:20)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2174:25)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1969:25)
    at TextEditorComponent.didMouseDownOnContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1805:25)
```

### Commands

```
  2x -0:06.2.0 tree-view:toggle (div.tool-panel.tree-view)
     -0:05.4.0 tree-view:toggle-vcs-ignored-files (div.tool-panel.tree-view)
```

### Non-Core Packages

```
apex-syntax 0.2.0 
apex-ui 1.0.1 
atom-elixir 0.2.3 
atom-typescript 11.0.7 
autocomplete-elixir 1.5.15 
build 0.68.0 
build-elixir 0.7.0 
busy 0.7.0 
busy-signal 1.4.3 
chestnut-light-atom-syntax 0.2.1 
clipboard-plus 0.5.1 
dash 1.7.1 
diffusion 0.0.0 
ex-mode 0.18.0 
git-blame 1.2.2 
go-debug 1.5.1 
go-plus 5.5.5 
go-signature-statusbar 1.2.3 
hyperclick 0.1.3 
intentions 1.1.5 
language-elixir 0.20.2 
language-scala 1.1.9 
linter 2.2.0 
linter-elixirc 1.7.0 
linter-ui-default 1.6.8 
sync-settings 0.8.3 
vim-mode-clipboard-plus 0.2.0 
vim-mode-plus 1.3.3 
vim-mode-plus-keymaps-for-surround 0.2.1 
```

**Comment by jclem** [comment]
Wow, obviously a duplicate.
