### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by elbow-jason** [wende/autocomplete-elixir#184]
I think I was typing `Kernel.<>` and this error occured.

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Linux Mint
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package 1.5.16

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /home/jason/.atom/packages/autocomplete-elixir/lib/autocomplete-elixir-provider.coffee:53

TypeError: Cannot read property '0' of null
    at RsenseProvider.module.exports.RsenseProvider.findSuggestions (/packages/autocomplete-elixir/lib/autocomplete-elixir-provider.coffee:53:14)
    at /packages/autocomplete-elixir/lib/autocomplete-elixir-provider.coffee:32:26
    at /packages/autocomplete-elixir/lib/autocomplete-elixir-client.coffee:31:7
    at /packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:68:5
    at Socket.fn (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:89:7)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
 12x -2:02.8.0 core:move-right (input.hidden-input)
  5x -1:59.8.0 core:backspace (input.hidden-input)
     -1:58.7.0 editor:newline (input.hidden-input)
     -1:57 core:backspace (input.hidden-input)
     -1:56.7.0 editor:newline (input.hidden-input)
  5x -1:56.3.0 core:backspace (input.hidden-input)
     -1:55.1.0 editor:newline (input.hidden-input)
  2x -1:52 core:backspace (input.hidden-input)
  2x -1:47.9.0 core:move-right (input.hidden-input)
     -1:46.5.0 editor:newline (input.hidden-input)
     -1:41.6.0 core:backspace (input.hidden-input)
     -0:20.9.0 editor:newline (input.hidden-input)
     -0:17.1.0 autocomplete-plus:confirm (input.hidden-input)
  2x -0:16.3.0 core:backspace (input.hidden-input)
     -0:15.6.0 editor:newline (input.hidden-input)
  7x -0:12.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-elixir 1.5.16 
busy-signal 1.4.3 
city-lights-syntax 1.1.4 
city-lights-ui 1.2.0 
intentions 1.1.5 
language-elixir 0.20.3 
linter 2.0.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
platformio-ide-terminal 2.7.0 
```

**Comment by elbow-jason** [comment]
Actually, as soon as I type `Kernel.` the autocomplete error occurs.

**Comment by elbow-jason** [comment]
Closing because this issue is a duplicate of #183
