### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by joaquinSilva** [wende/autocomplete-elixir#185]
Steps to reproduce:

1. I downloaded and installed node.js;
2. I installed Homebrew (successful install, but brew doctor showed the following unexpected header files that I left alone:
```
Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/node/android-ifaddrs.h
  /usr/local/include/node/libplatform/libplatform-export.h
  /usr/local/include/node/libplatform/libplatform.h
  /usr/local/include/node/libplatform/v8-tracing.h
  /usr/local/include/node/node.h
  /usr/local/include/node/node_api.h
  /usr/local/include/node/node_api_types.h
  /usr/local/include/node/node_buffer.h
  /usr/local/include/node/node_object_wrap.h
  /usr/local/include/node/node_version.h
  /usr/local/include/node/openssl/aes.h
  /usr/local/include/node/openssl/archs/BSD-x86/opensslconf.h
  /usr/local/include/node/openssl/archs/BSD-x86_64/opensslconf.h
  /usr/local/include/node/openssl/archs/VC-WIN32/opensslconf.h
  /usr/local/include/node/openssl/archs/VC-WIN64A/opensslconf.h
  /usr/local/include/node/openssl/archs/aix-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/aix64-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/darwin-i386-cc/opensslconf.h
  /usr/local/include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-aarch64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-armv4/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-elf/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-ppc/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-ppc64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-x32/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-x86_64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux32-s390x/opensslconf.h
  /usr/local/include/node/openssl/archs/linux64-s390x/opensslconf.h
  /usr/local/include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
  /usr/local/include/node/openssl/asn1.h
  /usr/local/include/node/openssl/asn1_mac.h
  /usr/local/include/node/openssl/asn1t.h
  /usr/local/include/node/openssl/bio.h
  /usr/local/include/node/openssl/blowfish.h
  /usr/local/include/node/openssl/bn.h
  /usr/local/include/node/openssl/buffer.h
  /usr/local/include/node/openssl/camellia.h
  /usr/local/include/node/openssl/cast.h
  /usr/local/include/node/openssl/cmac.h
  /usr/local/include/node/openssl/cms.h
  /usr/local/include/node/openssl/comp.h
  /usr/local/include/node/openssl/conf.h
  /usr/local/include/node/openssl/conf_api.h
  /usr/local/include/node/openssl/crypto.h
  /usr/local/include/node/openssl/des.h
  /usr/local/include/node/openssl/des_old.h
  /usr/local/include/node/openssl/dh.h
  /usr/local/include/node/openssl/dsa.h
  /usr/local/include/node/openssl/dso.h
  /usr/local/include/node/openssl/dtls1.h
  /usr/local/include/node/openssl/e_os2.h
  /usr/local/include/node/openssl/ebcdic.h
  /usr/local/include/node/openssl/ec.h
  /usr/local/include/node/openssl/ecdh.h
  /usr/local/include/node/openssl/ecdsa.h
  /usr/local/include/node/openssl/engine.h
  /usr/local/include/node/openssl/err.h
  /usr/local/include/node/openssl/evp.h
  /usr/local/include/node/openssl/hmac.h
  /usr/local/include/node/openssl/idea.h
  /usr/local/include/node/openssl/krb5_asn.h
  /usr/local/include/node/openssl/kssl.h
  /usr/local/include/node/openssl/lhash.h
  /usr/local/include/node/openssl/md4.h
  /usr/local/include/node/openssl/md5.h
  /usr/local/include/node/openssl/mdc2.h
  /usr/local/include/node/openssl/modes.h
  /usr/local/include/node/openssl/obj_mac.h
  /usr/local/include/node/openssl/objects.h
  /usr/local/include/node/openssl/ocsp.h
  /usr/local/include/node/openssl/opensslconf.h
  /usr/local/include/node/openssl/opensslv.h
  /usr/local/include/node/openssl/ossl_typ.h
  /usr/local/include/node/openssl/pem.h
  /usr/local/include/node/openssl/pem2.h
  /usr/local/include/node/openssl/pkcs12.h
  /usr/local/include/node/openssl/pkcs7.h
  /usr/local/include/node/openssl/pqueue.h
  /usr/local/include/node/openssl/rand.h
  /usr/local/include/node/openssl/rc2.h
  /usr/local/include/node/openssl/rc4.h
  /usr/local/include/node/openssl/ripemd.h
  /usr/local/include/node/openssl/rsa.h
  /usr/local/include/node/openssl/safestack.h
  /usr/local/include/node/openssl/seed.h
  /usr/local/include/node/openssl/sha.h
  /usr/local/include/node/openssl/srp.h
  /usr/local/include/node/openssl/srtp.h
  /usr/local/include/node/openssl/ssl.h
  /usr/local/include/node/openssl/ssl2.h
  /usr/local/include/node/openssl/ssl23.h
  /usr/local/include/node/openssl/ssl3.h
  /usr/local/include/node/openssl/stack.h
  /usr/local/include/node/openssl/symhacks.h
  /usr/local/include/node/openssl/tls1.h
  /usr/local/include/node/openssl/ts.h
  /usr/local/include/node/openssl/txt_db.h
  /usr/local/include/node/openssl/ui.h
  /usr/local/include/node/openssl/ui_compat.h
  /usr/local/include/node/openssl/whrlpool.h
  /usr/local/include/node/openssl/x509.h
  /usr/local/include/node/openssl/x509_vfy.h
  /usr/local/include/node/openssl/x509v3.h
  /usr/local/include/node/pthread-barrier.h
  /usr/local/include/node/stdint-msvc2008.h
  /usr/local/include/node/tree.h
  /usr/local/include/node/uv-aix.h
  /usr/local/include/node/uv-bsd.h
  /usr/local/include/node/uv-darwin.h
  /usr/local/include/node/uv-errno.h
  /usr/local/include/node/uv-linux.h
  /usr/local/include/node/uv-os390.h
  /usr/local/include/node/uv-posix.h
  /usr/local/include/node/uv-sunos.h
  /usr/local/include/node/uv-threadpool.h
  /usr/local/include/node/uv-unix.h
  /usr/local/include/node/uv-version.h
  /usr/local/include/node/uv-win.h
  /usr/local/include/node/uv.h
  /usr/local/include/node/v8-debug.h
  /usr/local/include/node/v8-inspector-protocol.h
  /usr/local/include/node/v8-inspector.h
  /usr/local/include/node/v8-platform.h
  /usr/local/include/node/v8-profiler.h
  /usr/local/include/node/v8-testing.h
  /usr/local/include/node/v8-util.h
  /usr/local/include/node/v8-value-serializer-version.h
  /usr/local/include/node/v8-version-string.h
  /usr/local/include/node/v8-version.h
  /usr/local/include/node/v8.h
  /usr/local/include/node/v8config.h
  /usr/local/include/node/zconf.h
  /usr/local/include/node/zlib.h

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
node
```
3. I installed Yarn using: `brew install yarn --without-node`
4. Then I downloaded and installed Atom, and placed the Atom application into my personal user applications folder instead of the public applications folder so it isn't visible to all users on this computer (only me when I log into my user account);
5. I downloaded and installed some Atom library packages;
6. I installed all the node packages by running yarn through terminal; and 
7. I opened the Atom application through the terminal and receive these repetitive looping error messages regarding elixir. I double checked to make sure that the paths for elixir were correct. I included screenshots of the settings for autocomplete elixir and of the looping error messages.

Symptoms:

1. Atom is taking a long time to respond when I first open the application and the screen is gray for several minutes before it takes me to the home screen of the app and I can access the panels, settings, and read the error messages.

2. Atom is receiving so many of these autocomplete elixir error messages that sometimes it will cause Atom app to freeze or crash. I previously received a prompt from Atom to send an error report about a crash, but the app froze and I wasn't able to capture and submit the data for analysis. 

![screen shot 2018-01-04 at 10 48 59 pm](https://user-images.githubusercontent.com/34997603/34596352-9d9a840a-f1a4-11e7-8398-b1eaf5f66601.png)
![screen shot 2018-01-04 at 11 10 07 pm](https://user-images.githubusercontent.com/34997603/34596358-a61b457e-f1a4-11e7-91d9-68f277fb1d38.png)

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package 1.5.16

### Stack Trace

Uncaught Error: spawn EACCES

```
At /Users/joaquinsilva/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:392

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at BufferedProcess.spawn (<embedded>:131312:63)
    at BufferedProcess.start (<embedded>:131118:20)
    at new BufferedProcess (<embedded>:131103:18)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:55:10)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:64:15)

```

### Commands

```
  7x -1:36.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.4 
angularjs 0.5.1 
angularjs-styleguide-snippets 0.9.1 
atom-beautify 0.30.9 
atom-jasmine 0.8.1 
atom-ternjs 0.18.3 
atom-typescript 11.0.10 
autoclose-html 0.23.0 
autocomplete-elixir 1.5.16 
babel-react-syntax 1.2.0 
clipboard-history 0.6.6 
duplicate-line-or-selection 0.9.0 
editorconfig 2.2.2 
emmet 2.4.3 
enhanced-tabs 1.7.0 
es6-javascript 1.0.0 
file-icons 2.1.15 
jumpy 4.2.0 
language-babel 2.81.1 
language-blade 0.38.0 
language-elixir 0.20.3 
linter 2.2.0 
linter-eslint 8.4.0 
linter-jshint 3.1.6 
linter-tslint 1.9.0 
linter-ui-default 1.6.10 
local-history 4.3.1 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-linter 2.1.3 
pigments 0.40.2 
pomodoro 1.2.0 
react 0.17.0 
react-native-snippets 0.3.0 
script 3.17.3 
seti-icons 1.5.4 
Stylus 3.1.1 
svg-preview 0.12.1 
```

**Comment by joaquinSilva** [comment]
I cleared the Saved State and reset Atom to factory settings and reinstalled atom packages and I can't reproduce this error. It seems to have resolved itself.
