### ISSUE TITLE
Uncaught Error: spawn E2BIG

### ISSUE THREAD

**Issue by znorris** [wende/autocomplete-elixir#190]
[Enter steps to reproduce:]

1. Open Atom
2. Add project directory where project directory contains an elixir project.

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.5
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package 1.5.16

### Stack Trace

Uncaught Error: spawn E2BIG

```
At /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:320

Error: spawn E2BIG
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at Object.exports.spawn (child_process.js:390:9)
    at BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:255:47)
    at BufferedProcess.start (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:82:18)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:69:18)
    at Object.exports.init (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:46:12)
    at exit (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:24:81)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -5:10.1.0 tree-view:toggle (button.btn.icon.enablement.icon-playback-play)
  2x -5:07.5.0 application:add-project-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-elixir 0.2.3 
atom-elixir-formatter 1.0.3 
atom-ide-ui 0.12.0 
atom-mermaid 3.3.1 
autocomplete-elixir 1.5.16 
base64 0.3.0 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
go-debug 1.6.2 
go-plus 5.8.3 
go-signature-statusbar 1.2.3 
hyperclick 0.0.0 
ide-python 1.0.0 
intentions 1.1.5 
language-docker 1.1.8 
language-elixir 0.22.0 
language-groovy 0.7.0 
language-lua 0.9.11 
language-systemd 0.1.1 
linter 2.2.0 
linter-docker 0.3.2 
linter-golinter 1.2.2 
linter-js-yaml 1.3.0 
linter-json-lint 0.1.3 
linter-ui-default 1.7.1 
nucleus-dark-ui 0.12.3 
one-black-syntax 1.14.0 
python-autopep8 0.1.3 
python-isort 0.0.7 
sort-lines 0.18.0 
split-diff 1.5.2 
sunset 1.2.1 
teletype 0.13.3 
yeti-syntax 0.1.2 
yeti-ui 0.1.6 
```

**Comment by znorris** [comment]
Closing after having read the README.md
