### ISSUE TITLE
Uncaught Error: spawn E2BIG

### ISSUE THREAD

**Issue by leandro-lugaresi** [wende/autocomplete-elixir#31]
The autocomplete throw ~a lot of~ exceptions After the setup of `erlangHome`config.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.2
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package, v1.4.2

### Stack Trace

Uncaught Error: spawn E2BIG

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn E2BIG
    at exports._errnoException (util.js:814:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:343:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:43:12)
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:47:34)
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:47:34)
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:47:34)
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:47:34)
```

### Commands

```
     -0:22.5.0 settings-view:open (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "todo-show",
      "Termrk",
      "elixir-cmd",
      "archive-view",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-ruby-on-rails"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "autocomplete-elixir": {
    "elixirPath": "/usr/local/bin/elixir",
    "erlangHome": "/usr/local/bin/erl"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-elixir, v1.4.2
language-elixir, v0.5.2
linter, v1.9.1
linter-php, v1.0.5
linter-phpcs, v1.2.2
linter-phpmd, v1.3.2
minimap, v4.15.0
php-cs-fixer, v2.5.1
project-manager, v2.6.5
vim-mode, v0.62.0
wakatime, v5.0.0

# Dev
No dev packages
```

**Comment by leandro-lugaresi** [comment]
The first exception was this:

**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package, v1.4.2


### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:26

RangeError: Maximum call stack size exceeded
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:26:9)
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:47:34)
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:47:34)
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:47:34)
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:47:34)
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:47:34)
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:47:34)
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:47:34)
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:47:34)
    at Object.exports.init (/Users/leandro/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:47:34)
```

**Comment by leandro-lugaresi** [comment]
I found the solution of this issue [here](https://github.com/wende/autocomplete-elixir/issues/19#issuecomment-138186152).
