### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Musashi178** [wende/autocomplete-elixir#52]
**Atom Version**: 1.7.2
**System**: Mac OS X 10.11
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package, v1.5.13

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At path.js:456

RangeError: Maximum call stack size exceeded
    at Array.join (native)
    at Object.posix.normalize (path.js:456:55)
    at Object.posix.join (path.js:488:16)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:21:12)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
    at Object.exports.init (/Users/marco/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:48:34)
```

### Commands

```
     -3:18.9.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -3:18.6.0 core:backspace (atom-text-editor.editor.is-focused)
 15x -3:17.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:01.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:53.2.0 core:save (atom-text-editor.editor.is-focused)
     -2:16.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:14.9.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -2:13.2.0 core:paste (atom-text-editor.editor.is-focused)
     -2:10.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "autocomplete-elixir": {
    "elixirPath": "/usr/local/bin/elixir",
    "erlangHome": "/usr/local/bin/erl"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-elixir, v1.5.13
file-icons, v1.7.4
language-elixir, v0.12.3

# Dev
No dev packages
```

# Versions
elixir v1.2.4
erl v18.3

**Comment by Musashi178** [comment]
Seems like I have misinterpret the "erlangHome" and entered the path to the erl executable rather than the path to the bin directory of erlang- Found the solution in #19
