### ISSUE TITLE
Uncaught Error: spawn E2BIG

### ISSUE THREAD

**Issue by BryanJBryce** [wende/autocomplete-elixir#53]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package, v1.5.13

### Stack Trace

Uncaught Error: spawn E2BIG

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:262

Error: spawn E2BIG
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:374:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:190:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at Object.exports.init (/Users/bryan/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:44:12)
    at exit (/Users/bryan/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:24:81)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-elixir, v1.5.13
language-elixir, v0.12.3

# Dev
No dev packages
```

**Comment by JakubCzarniecki** [comment]
👍

**Comment by JakubCzarniecki** [comment]
Atom Version: 1.7.3
System: Mac OS X 10.11.5
Thrown From: autocomplete-elixir package, v1.5.13

**Comment by viktorchukhantsev** [comment]
+1

**Comment by MichalMazurek** [comment]
+1
