### ISSUE TITLE
Uncaught Error: This socket is closed

### ISSUE THREAD

**Issue by baoxiehao** [wende/autocomplete-elixir#61]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.4
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package, v1.5.14

### Stack Trace

Uncaught Error: This socket is closed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1030

Error: This socket is closed
    at Socket._writeGeneric (net.js:673:19)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at Object.exports.loadFile (/Users/baoxiehao/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:77:7)
    at /Users/baoxiehao/.atom/packages/autocomplete-elixir/lib/autocomplete-elixir-client.coffee:19:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1144:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1114:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:904:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:738:18)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:693:35)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  3x -2:53.2.0 blur (input.hidden-input)
     -2:33.4.0 settings-view:open (input.hidden-input)
     -2:33.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
 16x -2:33.4.0 blur (input.hidden-input)
     -2:15.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
  9x -2:15.6.0 blur (button.btn.icon.enablement.icon-playback-play)
     -2:13.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
 23x -2:13.2.0 blur (input.hidden-input)
     -0:23.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
  9x -0:23.8.0 blur (button.btn.icon.enablement.icon-playback-pause)
     -0:19.5.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
 14x -0:19.5.0 blur (input.hidden-input)
     -0:15.5.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
  9x -0:15.5.0 blur (button.btn.icon.enablement.icon-playback-play)
  4x -0:02.9.0 core:backspace (input.hidden-input)
     -0:00.1.0 core:save (input.hidden-input)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "sync-settings",
      "language-gfm",
      "nuclide",
      "glowing-cursor"
    ],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-beautify, v0.29.12 (active)
atom-elixir, v0.2.1 (active)
atom-hexo, v1.1.1 (inactive)
atom-html-preview, v0.1.22 (active)
atom-htmltidy, v5.1.0 (active)
atom-live-server, v1.2.5 (inactive)
auto-reveal-active-file, v0.3.1 (active)
autocomplete-elixir, v1.5.14 (active)
autocomplete-erlang, v1.1.2 (active)
chary-tree-view, v0.2.3 (active)
elixir-cmd, v0.2.9 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.19 (active)
glowing-cursor, v0.1.1 (inactive)
hex, v0.6.2 (active)
highlight-selected, v0.11.2 (active)
iex, v0.9.27 (active)
keyboard-sounds, v0.2.0 (active)
language-babel, v2.37.0 (active)
language-elixir, v0.16.0 (active)
language-elm, v1.5.0 (active)
language-elmx, v1.2.7 (active)
language-erlang, v3.0.0 (active)
language-javascript-jsx, v0.3.7 (active)
language-markdown, v0.16.3 (active)
linter, v1.11.16 (active)
linter-elixirc, v1.1.11 (active)
linter-elm-make, v0.17.3 (active)
linter-erlang, v0.3.1 (active)
linter-javac, v1.9.4 (active)
markdown-assistant, v0.2.0 (active)
markdown-format, v2.5.1 (active)
markdown-pdf, v1.5.0 (inactive)
markdown-scroll-sync, v2.1.2 (active)
markdown-toc, v0.4.1 (inactive)
markdown-writer, v2.5.1 (active)
minimap, v4.24.7 (active)
nuclide, v0.165.0 (inactive)
open-in-browser, v0.4.7 (inactive)
open-recent, v5.0.0 (active)
pdf-view, v0.50.0 (active)
pigments, v0.34.0 (active)
platformio-ide-terminal, v2.2.0 (active)
qiniu-uploader, v0.0.3 (inactive)
regex-railroad-diagram, v0.16.0 (active)
script, v3.9.0 (inactive)
sepia-light-ui, v0.5.0 (inactive)
smalls, v0.2.0 (inactive)
sort-lines, v0.14.0 (inactive)
sync-settings, v0.7.2 (inactive)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by tomliversidge** [comment]
I was having this issue too. It looks like a possible duplicate of https://github.com/wende/autocomplete-elixir/issues/8

How are you opening Atom? try opening it from the command line inside the folder you want to start in:

`atom .`

this seems to fix it for me.

**Comment by baoxiehao** [comment]
@tomliversidge  I open the Atom from Mac docker first, and then open the elixir folder. I'll try your solution later, thanks for your  tips.
