### ISSUE TITLE
Uncaught Error: This socket is closed

### ISSUE THREAD

**Issue by vitnguyhiem** [wende/autocomplete-elixir#64]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package 1.5.14

### Stack Trace

Uncaught Error: This socket is closed

```
At /Users/vitnguyhiem/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:1045

Error: This socket is closed
    at Socket._writeGeneric (net.js:673:19)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at Object.exports.loadFile (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:77:7)
    at /packages/autocomplete-elixir/lib/autocomplete-elixir-client.coffee:19:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1082:27)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1049:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:890:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:44.6.0 core:move-right (input.hidden-input)
  3x -0:43.9.0 core:select-up (input.hidden-input)
  2x -0:42.5.0 core:backspace (input.hidden-input)
  2x -0:36.4.0 editor:newline (input.hidden-input)
     -0:29.7.0 snippets:next-tab-stop (input.hidden-input)
     -0:29.7.0 snippets:expand (input.hidden-input)
     -0:29.7.0 editor:indent (input.hidden-input)
 21x -0:29.1.0 core:backspace (input.hidden-input)
     -0:22.4.0 editor:newline (input.hidden-input)
  2x -0:21.5.0 core:undo (input.hidden-input)
     -0:18.5.0 snippets:next-tab-stop (input.hidden-input)
     -0:18.5.0 snippets:expand (input.hidden-input)
     -0:18.2.0 editor:newline (input.hidden-input)
  5x -0:17.3.0 core:undo (input.hidden-input)
 14x -0:13.7.0 core:backspace (input.hidden-input)
     -0:10.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-elixir 0.2.2 
atom-material-ui 1.3.9 
autocomplete-elixir 1.5.14 
highlight-column 0.5.2 
highlight-selected 0.12.0 
language-babel 2.54.1 
language-elixir 0.16.0 
```

**Comment by bsy** [comment]
+1

**Comment by SherSpock** [comment]
+1. I get this error most times I save

![image](https://cloud.githubusercontent.com/assets/14241275/23096195/05573db6-f5e5-11e6-9239-6666f0eb9881.png)

**Comment by SherSpock** [comment]
Opened #66 with reproduction steps. Feel free to close as duplicate, just trying to bump this issue.

I will be turning autocomplete off as it is too much of an impediment to productivity
