### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by ppolyzos** [wende/autocomplete-elixir#75]
Following this [example](https://m.alphasights.com/process-registry-in-elixir-a-practical-example-4500ee7c0dcc), when creating the `registry.ex` and typing the following
```
def send(room_name, message) do
    case whereis_name(room_name) do
      :undefined -> 
        {:badarg, {room_name, message}}

      pid -> 
        Kernel......
    end 
```
When you type `Kernel.` the error popups.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package 1.5.14

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/ppolyzos/.atom/packages/autocomplete-elixir/lib/autocomplete-elixir-provider.coffee:53

TypeError: Cannot read property '0' of null
    at RsenseProvider.module.exports.RsenseProvider.findSuggestions (/packages/autocomplete-elixir/lib/autocomplete-elixir-provider.coffee:53:14)
    at /packages/autocomplete-elixir/lib/autocomplete-elixir-provider.coffee:32:26
    at /packages/autocomplete-elixir/lib/autocomplete-elixir-client.coffee:31:7
    at /packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:68:5
    at Socket.fn (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:89:7)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
     -0:39.2.0 snippets:next-tab-stop (input.hidden-input)
     -0:39.2.0 snippets:expand (input.hidden-input)
     -0:39.2.0 editor:indent (input.hidden-input)
     -0:38.7.0 core:undo (input.hidden-input)
     -0:36 core:backspace (input.hidden-input)
  2x -0:32.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:30.6.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:29.5.0 core:undo (input.hidden-input)
     -0:27.3.0 autocomplete-plus:confirm (input.hidden-input)
     -0:26.6.0 core:backspace (input.hidden-input)
  2x -0:26 core:move-right (input.hidden-input)
  2x -0:24.5.0 editor:newline (input.hidden-input)
     -0:23.9.0 core:backspace (input.hidden-input)
  2x -0:12 editor:newline (input.hidden-input)
     -0:09.4.0 core:undo (input.hidden-input)
     -0:09.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
.bin undefined 
atom-beautify 0.29.17 
atom-jade 0.3.0 
atom-tsd 0.9.0 
atom-typescript 11.0.1 
autocomplete-elixir 1.5.14 
busy-signal 1.3.0 
file-icons 2.1.1 
intentions 1.1.2 
language-elixir 0.17.0 
language-powershell 4.0.0 
linter 2.1.2 
linter-csslint 1.3.4 
linter-elixirc 1.4.0 
linter-eslint 8.1.4 
linter-tslint 0.15.0 
linter-ui-default 1.2.2 
markdown-preview-plus 2.4.9 
react 0.16.2 
```

**Comment by jnfoote76** [comment]
Hey, did either of you end up solving this? I'm observing the exact same behavior.
