### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by optikfluffel** [wende/autocomplete-elixir#85]
**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package 1.5.14

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/udo/.atom/packages/autocomplete-elixir/lib/alchemide/doendmatcher.coffee:17

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.handleMatch (/packages/autocomplete-elixir/lib/alchemide/doendmatcher.coffee:17:35)
    at /packages/autocomplete-elixir/lib/autocomplete-elixir-client.coffee:21:23
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2187:33)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom Beta.app/Contents/Resources/app/src/selection.js:920:27)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/selection.js:41:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:248:33)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:53:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:421:26)
    at Marker.module.exports.Marker.update (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:362:18)
    at MarkerLayer.module.exports.MarkerLayer.restoreFromSnapshot (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:282:24)
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1517:85)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:958:20)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:910:20)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1672:32)
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2173:25)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1968:25)
    at TextEditorComponent.didMouseDownOnContent (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:1681:25)
```

### Commands

```
     -2:00.4.0 window:toggle-full-screen (atom-pane.pane.active)
  2x -2:00.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:53.5.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -1:51.7.0 core:confirm (input.hidden-input)
     -0:28.5.0 settings-view:open (a.stack-toggle)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-handlebars 1.3.0 
atom-ternjs 0.18.3 
atom-typescript 11.0.3 
autocomplete-elixir 1.5.14 
autocomplete-modules 1.6.10 
busy-signal 1.4.3 
css-snippets 1.1.0 
editorconfig 2.2.2 
elm-format 2.2.0 
elmjutsu 5.5.2 
ember-snippets 2.0.4 
file-icons 2.1.7 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.66.0 
language-csv 1.1.2 
language-docker 1.1.8 
language-elixir 0.19.0 
language-elm 1.5.0 
language-erlang 3.2.0 
language-gitignore 0.3.0 
language-haml 0.24.5 
language-haskell 1.12.1 
language-latex 1.0.0 
language-log 1.8.0 
language-markdown 0.23.0 
language-nginx 0.8.0 
language-riot-tag 0.2.2 
language-swift 0.5.0 
language-vue 0.23.0 
latex 0.44.0 
linter 2.2.0 
linter-csslint 1.3.4 
linter-docker 0.2.0 
linter-elixir-credo 1.1.0 
linter-elixirc 1.6.0 
linter-elm-make 0.23.2 
linter-eslint 8.2.1 
linter-golinter 1.2.2 
linter-haml 2.0.1 
linter-htmlhint 1.3.3 
linter-js-standard 3.9.1 
linter-jshint 3.1.2 
linter-markdown 4.0.1 
linter-scss-lint 3.1.0 
linter-swagger 0.4.1 
linter-tslint 1.6.0 
linter-ui-default 1.6.2 
minimap 4.28.2 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
pigments 0.39.1 
sort-lines 0.14.0 
standard-formatter 2.8.0 
trailing-spaces 0.4.0 
travis-ci-status 1.3.1 
tree-view-git-status 1.4.0 
url-encode 0.5.0 
```

**Comment by narrowtux** [comment]
I have the same issue. It happens whenever I click to move the cursor in a `.ex` file.
