### ISSUE TITLE
Uncaught Error: This socket is closed

### ISSUE THREAD

**Issue by kirillivanov** [wende/autocomplete-elixir#86]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package 1.5.14

### Stack Trace

Uncaught Error: This socket is closed

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:1095

Error: This socket is closed
    at Socket._writeGeneric (net.js:673:19)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at Object.exports.loadFile (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:77:7)
    at /packages/autocomplete-elixir/lib/autocomplete-elixir-client.coffee:19:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:33)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:780:24)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:763:25)
    at Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1548:46)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:236:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:03.6.0 core:backspace (input.hidden-input)
  4x -0:03.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
apex-syntax 0.1.0 
apex-ui 0.2.1 
autocomplete-elixir 1.5.14 
busy-signal 1.4.3 
flatwhite-syntax 0.8.1 
gruvbox-plus-syntax 1.3.1 
Hydrogen 1.17.1 
intentions 1.1.2 
language-elixir 0.19.0 
linter 2.2.0 
linter-elixirc 1.6.0 
linter-ui-default 1.6.2 
northem-light-atom-syntax 2.1.0 
pristine-ui 1.0.15 
scroll-through-time 0.2.0 
zentabs 0.8.8 
```

**Comment by mager** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package 1.5.14


### Stack Trace

Uncaught Error: This socket is closed

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:1095

Error: This socket is closed
    at Socket._writeGeneric (net.js:673:19)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at Object.exports.loadFile (/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:77:7)
    at /packages/autocomplete-elixir/lib/autocomplete-elixir-client.coffee:19:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:33)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:780:24)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:763:25)
    at Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1548:46)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:236:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:41.4.0 atom-elixir:autocomplete-enter (input.hidden-input)
     -0:41.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:41.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:40.6.0 core:paste (input.hidden-input)
     -0:38.2.0 core:copy (input.hidden-input)
     -0:37.3.0 core:paste (input.hidden-input)
  2x -0:30.4.0 core:save (input.hidden-input)
  2x -0:14.9.0 core:copy (input.hidden-input)
     -0:14.1.0 find-and-replace:select-next (input.hidden-input)
     -0:13.8.0 core:paste (input.hidden-input)
     -0:06.7.0 core:copy (input.hidden-input)
     -0:06.2.0 find-and-replace:show (input.hidden-input)
     -0:06.0 core:paste (input.hidden-input)
  3x -0:05.8.0 core:confirm (input.hidden-input)
     -0:04.6.0 find-and-replace:show-previous (input.hidden-input)
     -0:01.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
apex-syntax 0.1.0 
apex-ui 0.2.1 
atom-beautify 0.30.4 
atom-clock 0.1.13 
atom-django 0.3.2 
atom-elixir 0.2.3 
atom-formatter-jsbeautify 1.1.2 
atomify 0.6.0 
autocomplete-elixir 1.5.14 
busy-signal 1.4.3 
chestnut-light-atom-syntax 0.2.1 
electron-highlighter-syntax 1.9.0 
flatwhite-syntax 0.8.1 
geany-github-syntax 1.0.0 
github-atom-light-syntax 0.5.0 
graphite-ui 0.15.1 
Hydrogen 1.19.0 
intentions 1.1.5 
language-babel 2.68.0 
language-elixir 0.19.0 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-elixirc 1.7.0 
linter-pycodestyle 2.0.2 
linter-ui-default 1.6.3 
loved-syntax 1.0.2 
paper-flat-ui 1.3.6 
phoenix-elixir-snippets 0.4.0 
prettier-atom 0.37.0 
react-native-snippets 0.3.0 
react-snippets 0.8.0 
tomorrow-night-bright-syntax 0.1.0 
wakatime 7.0.3 
```
