### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by fstiffo** [wende/autocomplete-elixir#96]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package 1.5.14

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Francesco\.atom\packages\autocomplete-elixir\lib\alchemide\doendmatcher.coffee:17

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.handleMatch (/packages/autocomplete-elixir/lib/alchemide/doendmatcher.coffee:17:35)
    at /packages/autocomplete-elixir/lib/autocomplete-elixir-client.coffee:21:23
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.cursorMoved (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor.js:2187:33)
    at Selection.module.exports.Selection.markerDidChange (~/AppData/Local/atom/app-1.19.0/resources/app/src/selection.js:920:27)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/selection.js:41:30
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/text-buffer/lib/display-marker.js:248:33)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/text-buffer/lib/display-marker.js:53:32
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Marker.module.exports.Marker.emitChangeEvent (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/text-buffer/lib/marker.js:424:26)
    at Marker.module.exports.Marker.update (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/text-buffer/lib/marker.js:365:18)
    at MarkerLayer.module.exports.MarkerLayer.restoreFromSnapshot (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/text-buffer/lib/marker-layer.js:282:24)
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1516:85)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:950:20)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:902:20)
    at TextEditor.module.exports.TextEditor.transact (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor.js:1672:32)
    at TextEditor.module.exports.TextEditor.moveCursors (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor.js:2173:25)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor.js:1968:25)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:1717:25)
```

### Commands

```
     -6:10.4.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -6:06.1.0 application:add-project-folder (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
autocomplete-elixir 1.5.14 
busy-signal 1.4.3 
custom-invisibles 0.1.2 
elm-format 2.2.0 
elmjutsu 5.6.2 
html-to-elm 0.2.0 
intentions 1.1.5 
language-dtd 0.2.1 
language-elixir 0.19.0 
language-elm 1.5.0 
language-prolog 0.11.0 
linter 2.2.0 
linter-elixirc 1.7.0 
linter-elm-make 0.23.7 
linter-prolog 0.2.0 
linter-ui-default 1.6.3 
minimap 4.29.3 
monokai 0.24.0 
```

**Comment by samba6** [comment]
Go to ...\.atom\packages\autocomplete-elixir\lib\alchemide\doendmatcher.coffee, find the line with this code: `lastLineNo = editor.buffer.lines.length - 1` and change to `lastLineNo = editor.buffer.getLines().length - 1`.

Hope it helps.
